name: ğŸš€ Frontend Dependency Update and Vulnerability Scan

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-and-scan-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ—‘ï¸ Remove package-lock.json
        run: rm -f package-lock.json
        working-directory: frontend

      - name: ğŸ“¦ Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: â¬†ï¸ Update dependencies in package.json
        run: ncu -u
        working-directory: frontend

      - name: ğŸ“¦ Install dependencies
        run: npm install
        working-directory: frontend

      - name: ğŸ“¦ Update dependencies with legacy peer deps
        run: npm update --legacy-peer-deps
        working-directory: frontend

      - name: ğŸ­ Mask Debricked credentials
        run: echo "::add-mask::${{ secrets.DEBRICKED_TOKEN }}"

      - name: Install Debricked CLI
        run: |
          curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
          sudo mv debricked /usr/local/bin/debricked

      - name: ğŸ›¡ï¸ Debricked Vulnerability Scan
        run: |
          debricked scan -t ${{ secrets.DEBRICKED_TOKEN }} -r ${{ github.repository }} -c ${{ github.sha }}
        working-directory: frontend

      - name: ğŸ“ Commit changes
        if: success()
        run: |
          git config --local user.name "Debugging Duck ğŸ¦†"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add frontend/package.json frontend/package-lock.json
          git diff-index --quiet HEAD || git commit -m "â¬†ï¸ update all frontend npm dependenciesâ¬†ï¸"

      - name: ğŸš€ Push changes
        if: success()
        run: git push
